INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Suzuki","GSX-R",600,"Stradale");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Kawasaki","Ninja",600,"Stradale");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Ducati","Diavel",1200,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Ducati","Panigale",1300,"Stradale");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Ducati","Panigale",960,"Stradale");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Ducati","Panigale",960,"Stradale");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Aprilia","Caponord",1200,"Multiroad");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Aprilia","Dorsoduro",750,"Multiroad");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Aprilia","Mana",850,"Multiroad");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Aprilia","RS4",125,"Stradale");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Aprilia","RSV4",1000,"Stradale");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Aprilia","SL Shiver",750,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Aprilia","Tuono",1100,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Benelli","BN",250,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Benelli","BN",300,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Benelli","BN",600,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Benelli","Tornado",900,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Benelli","Tre",1130,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","F GS",700,"Multiroad");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","F GS",800,"Multiroad");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","F GT",800,"Multiroad");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","F R",800,"Multiroad");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","R GS",1200,"Multiroad");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","R RS",1200,"Multiroad");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","R R",1200,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","G R",310,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","R nineT",1200,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","S R",1000,"Naked");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","S RR",1000,"Stradale");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("BMW","S XR",1000,"Multiroad");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Cagiva","Mito",125,"Stradale");
INSERT INTO Moto (Marca,Modello,Cilindrata,Categoria) VALUES ("Cagiva","Raptor",125,"Naked");
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Adria Raceway","Italia",2072);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Circuito Del Sele","Italia",1360);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Franciacorta","Italia",1501);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Imola","Italia",4933);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Misano","Italia",4180);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Monza","Italia",5793);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Mugello","Italia",5245);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Vallelunga","Italia",4110);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Losail","Quatar",5380);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Jerez","Spagna",4423);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Estoril","Portogallo",4182);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Le Mans","Francia",4180);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Catalunya","Spagna",4655);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Assen","Olanda",4555);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Laguna Seca","Stati Uniti",3610);
INSERT INTO Circuito (Nome,Nazione,Lunghezza) VALUES ("Philip Island","Australia",4448);

